version: '3.9'

services:
  nexus-app:
    depends_on:
      - nexus-db
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: nestjs-docker
    # image: localhost/marcacion-backend
    #container_name: nestjsapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    networks:
      - network-nexus

  nexus-db:
    image: postgres:15.2-alpine
    container_name: ${DB_HOST}
    restart: always
    ports:
      - 5453:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      TZ: 'America/El_Salvador'
      PGTZ: 'America/El_Salvador'
    networks:
      - network-fac

networks:
  network-nexus: 